### ISSUE TITLE
Doesn't run any tests

### ISSUE THREAD

**Issue by garrettlancaster** [seattlerb/minitest-focus#5] opened 2013-11-22 17:42 UTC
I am using the describe/it format, minitest 4.7.5 and ruby 1.9.3.  When I add 

```ruby
focus
it "should..." do
...
end
```
I get `0 tests, 0 passed, 0 failures, 0 errors, 0 skips, 0 assertions`

Not sure if it's relevant, but I am inside a second level `describe` and am using an after block.

**Comment by CyborgMaster** [comment] 2015-03-02 17:33
I can confirm that this happens anytime the test is contained inside a describe block.  I'm going to try and see if i can figure out what is causing this.

**Comment by CyborgMaster** [comment] 2015-03-02 18:04
Ok, so I was mistaken.  I looks like nested describe blocks are working fine for me.  My problem was parenthesis in the name, which is the issue describe in #3.

I recommend this issue be closed.

**Comment by zenspider** [comment] 2015-04-13 22:52
Closing

**Closed by zenspider** 2015-04-13 22:52 UTC
